# Generated by Django 5.0.4 on 2024-04-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', models.CharField(max_length=256)),
                ('to_country', models.CharField(max_length=256)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('from_place', models.CharField(max_length=256)),
                ('to_place', models.CharField(max_length=256)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
